/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SettingsImport } from './routes/settings'

// Create Virtual Routes

const PrevSitesLazyImport = createFileRoute('/prev-sites')()
const AboutGamerLazyImport = createFileRoute('/about-gamer')()
const AboutDeveloperLazyImport = createFileRoute('/about-developer')()
const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const PrevSitesLazyRoute = PrevSitesLazyImport.update({
  path: '/prev-sites',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/prev-sites.lazy').then((d) => d.Route))

const AboutGamerLazyRoute = AboutGamerLazyImport.update({
  path: '/about-gamer',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about-gamer.lazy').then((d) => d.Route))

const AboutDeveloperLazyRoute = AboutDeveloperLazyImport.update({
  path: '/about-developer',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/about-developer.lazy').then((d) => d.Route),
)

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const SettingsRoute = SettingsImport.update({
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/about-developer': {
      preLoaderRoute: typeof AboutDeveloperLazyImport
      parentRoute: typeof rootRoute
    }
    '/about-gamer': {
      preLoaderRoute: typeof AboutGamerLazyImport
      parentRoute: typeof rootRoute
    }
    '/prev-sites': {
      preLoaderRoute: typeof PrevSitesLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  SettingsRoute,
  AboutLazyRoute,
  AboutDeveloperLazyRoute,
  AboutGamerLazyRoute,
  PrevSitesLazyRoute,
])

/* prettier-ignore-end */
